version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: tutorlink_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 001122
      POSTGRES_DB: tutor_link
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: